Jump to date
martinpitt/performance-graphs pull request #54
Opened 2020-09-23 19:06 UTC by marusak

Fixes #35

![jumpy](https://user-images.githubusercontent.com/12330670/94057900-90ad4e80-fde0-11ea-8643-3077e05eb81f.png)
![menu](https://user-images.githubusercontent.com/12330670/94057915-960a9900-fde0-11ea-94b1-aaf8b6374824.png)

2020-09-23 19:06 UTC, marusak commented on test/check-application
> +        # FIXME - oh for fox sake, why pcp is so difficult?
This is annoying...

2020-09-24 08:45 UTC, martinpitt commented
Thanks for working on this, this is really cool! On a freshly booted VM I noticed that when going to a past date, I still see the current hour:

![image](https://user-images.githubusercontent.com/200109/94122466-ddca0880-fe52-11ea-8b91-a355260a09f7.png)

I don't have any past data yet (going to figure out how to synthesize these now), but this looks a bit odd? What happens in your case when you do have past data?

2020-09-24 08:56 UTC, marusak commented
> On a freshly booted VM I noticed that when going to a past date, I still see the current hour:

Interesting. I can reproduce this on a VM, will try to figure out what is happening.

> What happens in your case when you do have past data?

Just loads the whole day and I see one day from midnight to midnight.

2020-09-24 09:13 UTC, marusak commented
Hmm, so it seems that `this.load_data(sel, 24 * SAMPLES_PER_H)` returns today even though `sel` is a timestamp representing `22.9.2020 0:0:0` and I request only 24 hours of data but it still reads up to today.

2020-09-24 10:13 UTC, martinpitt requested changes
Thanks! I didn't look at the tests yet, will do in the next round.

2020-09-24 10:13 UTC, martinpitt commented on src/app.jsx
> +                <div className="metrics-history-heading-sticky">
This was previously guarded by `this.state.hours.length > 0`. I see how we don't want to do that any more, as a particular day may not have any data. But we still must not show this if pcp is not available, or there's some other error condition.

2020-09-24 10:13 UTC, martinpitt commented on src/app.jsx
> +                            <span>{_("Jump to")}</span>
I'd like to entirely drop this label. The selection should speak for itself, and if "Current" becomes "Today" or "Now", it's hopefully clearer? If not, then perhaps "Change day:"?

2020-09-24 10:13 UTC, martinpitt commented on src/app.jsx
> +                                aria-label="Select day"
needs i18n, and should be identical to the above span (if you want to keep that).

2020-09-24 10:20 UTC, marusak commented on src/app.jsx
> +            this.load_data(sel - LOAD_HOURS * MSEC_PER_H);
This is because when you go to current we want to stream new data. That is achieved by calling `load_data()` without the second argument. I guess I could just conditional the second argument. (And also ignore 12 vs 24 hours or conditional that one as well).

2020-09-24 10:21 UTC, marusak commented on src/app.jsx
> +            nodata_alert = <EmptyStatePanel icon={ExclamationCircleIcon} title={_("No data available")} />;
This happens in the test. If you just run the test you would see it right after you log in.
This was mostly just experimenting with tests and indeed it should be separate commit.

2020-09-24 10:25 UTC, marusak commented on src/app.jsx
> +        const options = [<SelectOption key={this.state.currentDate} value={this.state.currentDate}>{_("Current")}</SelectOption>];
> would it make more sense to use a special value null or "0" or "" instead of an actual timestamp?

:) I had there `0` but since (I assume) there is check like `if key` it was not working. Having `1` worked fine. So I though that just having the timestamp instead of some random value made more sense.

> Proposal: Change string to "Now" or "Today".

'Now' could work. Today might be confusing as there is "Today" in the form of `24.9`.

2020-09-24 10:26 UTC, marusak commented on src/app.jsx
> +                            <span>{_("Jump to")}</span>
@garrett

2020-09-24 11:39 UTC, garrett commented
Why is there a bunch of blank space at the top of the graphs? (I guess this has nothing to do with the PR though...)

2020-09-24 11:46 UTC, marusak commented
> Why is there a bunch of blank space at the top of the graphs? (I guess this has nothing to do with the PR though...)

Bacause I took the screenshot at 21:10 or so, so the remaining 50 minutes are shown like that.

2020-09-24 12:15 UTC, garrett commented
> Bacause I took the screenshot at 21:10 or so, so the remaining 50 minutes are shown like that.

Ah, ok. We might want to change that behavior. Later, in another PR, of course.

Back to this PR:

The alignment of the bar is off. I could fix that. I'll build a VM and see what I can do here.

2020-09-25 08:00 UTC, marusak commented on src/app.jsx
> +                <div className="metrics-history-heading-sticky">
> But we still must not show this if pcp is not available, or there's some other error condition.

Sure, that works. in the `render()` method we `return` if there is no `cockpit-pcp`, `metrics could not be loaded` or `Error has occurred`. We show this heading only with 'No data available between...` or the new 'No data available' (which happens when there are some data, but no data newer than the selected date).

2020-09-25 08:34 UTC, marusak commented
@martinpitt I addressed all your comments. It does not yet implement the "if (limit && loaded_hour > from_timestamp + limit)" thing.

2020-09-25 08:54 UTC, martinpitt commented
@garrett:

> Why is there a bunch of blank space at the top of the graphs?

Because we auto-refresh the page every minute, so we want/need some empty space that the graph can grow into; otherwise the entire page would jump every minute. I'm of course happy to revisit this, that was just the original reason.

2020-09-25 09:14 UTC, martinpitt requested changes
Cheers!

2020-09-25 09:14 UTC, martinpitt commented on src/app.jsx
> +        // Timestamp of `date +%s`
Not quite, it's the timestamp of current hour, not the actual time. I.e. should get a better name (current_hour?) and comment.

2020-09-25 09:14 UTC, martinpitt commented on src/app.jsx
> +                        this.now = current_hour;
You can then spare the `const current_hour`, and just directly use `this.current_hour =`.

2020-09-25 09:14 UTC, martinpitt commented on src/app.jsx
> +                            selectedDate: current_hour,
Feels a bit weird that you define a `const selected` above, but it's not what you actually use here. Semantically, as this is a day picker, wouldn't "today's timestamp" (i.e. at midnight) be a more logical value for the selection, as the earlier days are all at midnight as well?

**Update**: I think I understand the intention now: for "now" we preload 12 hours, but for "today" we preload 24 hours.

2020-09-25 09:14 UTC, martinpitt commented on src/app.jsx
> +        for (let i = 0; i < 14; i++) {
So this means that in the morning up to noon, "now" and today's date will have exactly the same effect, right? In the afternoon, the first few hours of the day will be missing for "Now". That feels a bit icky, but I do agree that we don't want to preload too much by default. So let's keep that for now.

2020-09-25 09:14 UTC, martinpitt commented on test/check-application
> +        # FIXME - oh for fox sake, why pcp is so difficult?
Indeed, but pretty much no software is handling backwards time jumps well. I'd say, we just ignore that. Let's just tame down the comment a little :-)

2020-09-25 09:14 UTC, martinpitt commented on test/check-application
> +        b.click(".pf-c-select__menu-item:contains('Wednesday, Sep 16, 2020')")
We have `b.select_PF4()`, which may simplify this a little bit.

2020-09-25 09:14 UTC, martinpitt commented on test/check-application
> +        testlib.sit()
Let's just drop that then if it doesn't work.

2020-09-25 09:24 UTC, martinpitt commented
I tested that interactively (again, without old data, though), and aside from the "selected range overflow" it works fine. Thanks!

2020-09-25 10:18 UTC, marusak commented on src/app.jsx
> +                            selectedDate: current_hour,
Ok, I gave this a bit more thought and I think having "Now" and today's date is just confusing. I have changed it to "Today", "<yesterday's date>"...
Selecting today will show everything from the midnight up until now and starts streaming. There is slight difference as when you open the page it loads just 12 hours and shows 'Today' as the current hour, but if you pick 'Today' again it will show up to 24hours of data. But honestly I don't think that anyone will be bothered by this - they have some data when they visit the page, if they need some earlier data they can click on the button. Or if you think it would be better we can always load everything from the midnight up until now. It can in some early morning hours show barely anything which is not great.

2020-09-25 10:39 UTC, marusak commented
Updated as I commented above.

2020-09-25 10:40 UTC, marusak commented
I'll open issue for the overflow once this lands.

2020-09-25 10:55 UTC, martinpitt commented on src/app.jsx
> +                            selectedDate: current_hour,
I agree, this is a nice compromise. Thanks!

2020-09-25 12:14 UTC, martinpitt commented on test/check-application
> +        # self.waitStream(3) # FIXME: wait for new data - pcp does not handle time change greatly
BTW, it might do that if you stop and start pmlogger around the time change, like we do in prepareArchive()

2020-09-25 12:20 UTC, martinpitt approved these changes
Thanks! Good enough now to land. When you file the issue about the "overflow" issue, can you please mark it release-blocker?

2020-09-25 12:20 UTC, martinpitt commented on test/check-application
> +        self.assertGreater(getMaximumSpike(b, "memory", False, 1600236000000, 53), 0.8)
Feels a bit magic here that getMaximumSpike() would wait for the graph to refresh.. but it obviously works :)

2020-09-25 12:20 UTC, merged