Hide ruler tick marks for nonexisting graphs
martinpitt/performance-graphs pull request #64
Opened 2020-09-25 13:45 UTC by martinpitt

Disk/net saturation graphs are not a thing, so don't render the ruler
tick marks for these.

For that, split the `border-top` property into two halfes, and 
conditionalize the right half on a new `.have-saturation` class.

Fixes #60 

 - [ ] Builds on top of PR #62

2020-09-25 13:48 UTC, martinpitt commented
This is mostly a design decision - both "do we want this at all?" and "does the CSS make sense", so @garrett, could you please review this one?

The effect is that the ruler tick marks on Disks/Network are gone:

![image](https://user-images.githubusercontent.com/200109/94274836-79887100-ff46-11ea-981e-3af22c8b3bb3.png)

2020-09-25 13:48 UTC, martinpitt commented
We could do the same to "memory load", i. e. not show ticks if the machine does not have swap.

2020-09-27 10:55 UTC, marusak commented
Could we do something with that empty space that is left after half of the graphs were removed?

2020-09-28 08:17 UTC, garrett commented
Network and IO have saturation though? https://www.brendangregg.com/USEmethod/use-linux.html


component | type | metric
-- | -- | --
Network Interfaces | saturation | ifconfig, "overruns", "dropped"; netstat -s, "segments retransmited"; sar -n EDEV, *drop and *fifo metrics; /proc/net/dev, RX/TX "drop"; nicstat "Sat" [6]; dynamic tracing for other TCP/IP stack queueing [7]
Storage device I/O | saturation | iostat -xnz 1, "avgqu-sz" > 1, or high "await"; sar -d same; LPE block probes for queue length/latency; dynamic/static tracing of I/O subsystem (incl. LPE block probes)

I guess equivalents dont exist in PCP though?

2020-09-28 08:23 UTC, garrett commented
Regarding the UI, yeah, it should probably be adapted as to remove the blank space.

This being the case, we probably should also trim down the swap on memory so it's not the same width of physical RAM. Perhaps half the width? We could make it proportional, but it's generally bad practice to do so (as IO latency is way, way, way slower than RAM, so you'd only want a bit of overflow, instead of the same size as RAM — unless one is using suspend-to-disk, but it doesn't work on encrypted filesystems anyway, and isn't relevant for servers.

So if someone had 40 GiB of RAM + 4 GiB swap, proportional swap might look too small at just 10%. We could make it proportional within bounds though (with a minimum and maximum)... or just make it a fixed size, like 50% or 25% of the width of the RAM or something like that.

WDYT?

2020-09-28 08:30 UTC, garrett commented
If we just scaled the IO and network to be the same width as the rest, we'd get something like this:

![metrics-scaled](https://user-images.githubusercontent.com/10246/94408668-65768680-0175-11eb-9608-d3520ffe0f6e.png)

However, if we dropped the extra space and adjusted the swap so that it's something around 25% to 33% of RAM (as ideally, you wouldn't use much of any of swap), we'd have something like this:

![metrics-cropped](https://user-images.githubusercontent.com/10246/94408666-64455980-0175-11eb-8cb0-3c20b1306e57.png)

This second mockup (in this case, a manipulated screenshot) is what I'm suggesting.

2020-09-28 08:34 UTC, martinpitt commented
@garrett : The memory saturation is *not* swap usage, but swap *events* -- it's showing how many pages are being swapped out (so, approximately the derivative of swap usage).

I like the approach of removing the empty space and adjusting the vertical ruler and table headings!

2020-09-28 09:12 UTC, garrett commented
> The memory saturation is not swap usage, but swap events

Ah! All the more reason to collapse it down in size then. Right?

2020-09-28 09:41 UTC, martinpitt commented
@garrett: Not sure -- I actually quite like the graphs being symmetric..

2020-10-01 06:53 UTC, marusak commented
>  I like the approach of removing the empty space and adjusting the vertical ruler and table headings!

Me too. I feel like there is no good reason for wasting that much space

2020-10-01 11:54 UTC, marusak commented
This PR now looks like this:
![nowpitti](https://user-images.githubusercontent.com/12330670/94805832-4eda6480-03ed-11eb-9f0d-bd34b1eca700.png)

I have changes ready after which it looks like this:
![nowmine](https://user-images.githubusercontent.com/12330670/94805876-5e59ad80-03ed-11eb-8612-6d39c07ef24c.png)

@garrett @andreasn @martinpitt Which one do you prefer?

2020-10-01 11:54 UTC, marusak commented
One issue I just noticed is that svgs are not correctly sized (notice expanded minutes in top and bottom screens)

2020-10-01 12:08 UTC, marusak commented
> One issue I just noticed is that svgs are not correctly sized (notice expanded minutes in top and bottom screens)

Have a local fix.

2020-10-01 12:15 UTC, martinpitt commented
@marusak: I definitively prefer your version, to not waste that space. We also still need to attach some individual labels to the graphs, after that it should hopefully become clearer.

2020-10-01 12:18 UTC, andreasn commented
> Which one do you prefer?

I prefer version 2. The version above looks like something is missing.

2020-10-01 12:52 UTC, marusak commented
Pushed here also sublabels, now looks like this:
![newandshiny](https://user-images.githubusercontent.com/12330670/94811485-b85e7100-03f5-11eb-9857-4adcd05adfd9.png)

2020-10-01 14:04 UTC, andreasn requested changes
UX is good, but might want to switch to Pattenfly colors.
Mostly worried about this, since a dark theme variant is in the works in Patternfly, so it might bite us down the road if we use hard-colored colors.

2020-10-01 14:04 UTC, andreasn commented on src/app.scss
> +        color: rgba(0,0,0,0.7);
Maybe better to use a predefined patternfly color here.
https://www.patternfly.org/v4/guidelines/colors#typography-and-iconography-colors

2020-10-01 14:04 UTC, andreasn commented on src/app.scss
> +            border-right: 1px solid rgba(0,0,0,0.3);
Same as above.
https://www.patternfly.org/v4/guidelines/colors#typography-and-iconography-colors

2020-10-01 14:04 UTC, andreasn commented on src/app.scss
> +            border-top: 1px solid rgba(0,0,0,0.3);
Same as above
https://www.patternfly.org/v4/guidelines/colors#typography-and-iconography-colors

2020-10-01 14:33 UTC, garrett commented
Super cool.

I guess the PF colors could be problematic due to the need of alpha transparency.

2020-10-01 14:36 UTC, garrett commented
A dark theme would bite us in several other ways. That's why I opened up https://github.com/cockpit-project/cockpit/issues/10189 exactly two years ago to the date, and why we've been waiting on PF to finish implementing it. :wink:

2020-10-01 14:38 UTC, andreasn commented
@garrett if you're not worried about the color values, then I trust your judgement. So Good to Go in that case.

2020-10-01 14:40 UTC, garrett approved these changes
:+1: Looks good to me

2020-10-01 14:43 UTC, andreasn approved these changes
Garrett convinced me to not worry about the colors for now, so good to go for me.

2020-10-01 14:48 UTC, garrett commented
Ideally, PatternFly would have a class for dark mode. IIRC, they would enable it at the top of the page _or_ at a specific widget level.

So we could do something like this in SCSS:

```scss
.foo {
   color: var(--some-color);
  .dark-mode & {
     --some-color: #fff;
     background: red;
  }
}
```

And SASS would unwrap that as:

```scss
.foo { ... }
.dark-mode .foo { ... }
```

And the specificity of the dark mode overrides would win out. It would also be afterward too. :wink:

FWIW: PF would probably go with `.pf-m-darkmode` or something such.

2020-10-01 17:01 UTC, merged

2020-10-01 17:15 UTC, martinpitt commented
@marusak: congrats! zero open PRs left \o/

2020-10-01 17:27 UTC, marusak commented
> zero open PRs left \o/

That was the second item in https://github.com/cockpit-project/cockpit/pull/14678 and now I can reimport and fix other issues :)